# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/acer/salsa/extract-files.sh - DO NOT EDIT

# All the blobs necessary for salsa
PRODUCT_COPY_FILES += \
    vendor/acer/salsa/proprietary/libEGL_adreno200.so:system/lib/egl/libEGL_adreno200.so \
    vendor/acer/salsa/proprietary/libGLESv2_adreno200.so:system/lib/egl/libGLESv2_adreno200.so \
    vendor/acer/salsa/proprietary/libGLESv1_CM_adreno200.so:system/lib/egl/libGLESv1_CM_adreno200.so \
    vendor/acer/salsa/proprietary/libq3dtools_adreno200.so:system/lib/egl/libq3dtools_adreno200.so \
    vendor/acer/salsa/proprietary/libgsl.so:system/lib//libgsl.so \
    vendor/acer/salsa/proprietary/yamato_pfp.fw:system/etc/firmware/yamato_pfp.fw \
    vendor/acer/salsa/proprietary/yamato_pm4.fw:system/etc/firmware/yamato_pm4.fw \
    vendor/acer/salsa/proprietary/BCM4325.hcd:system/etc/firmware/BCM4325.hcd \
    vendor/acer/salsa/proprietary/BCM4325.bin:system/etc/wifi/BCM4325.bin \
    vendor/acer/salsa/proprietary/BCM4325_apsta.bin:system/etc/wifi/BCM4325_apsta.bin \
    vendor/acer/salsa/proprietary/BCM4325Fac.bin:system/etc/wifi/BCM4325Fac.bin \
    vendor/acer/salsa/proprietary/nvram.txt:system/etc/wifi/nvram.txt \
    vendor/acer/salsa/proprietary/qmuxd:system/bin/qmuxd \
    vendor/acer/salsa/proprietary/brcm_patchram_plus:system/bin/brcm_patchram_plus \
    vendor/acer/salsa/proprietary/libril-acer-1.so:system/lib/libril-acer-1.so \
    vendor/acer/salsa/proprietary/libril-acerril-hook-oem.so:system/lib/libril-acerril-hook-oem.so \
    vendor/acer/salsa/proprietary/libdiag.so:system/lib/libdiag.so \
    vendor/acer/salsa/proprietary/liboncrpc.so:system/lib/liboncrpc.so \
    vendor/acer/salsa/proprietary/libqmi.so:system/lib/libqmi.so \
    vendor/acer/salsa/proprietary/libdsm.so:system/lib/libdsm.so \
    vendor/acer/salsa/proprietary/libqueue.so:system/lib/libqueue.so \
    vendor/acer/salsa/proprietary/libdll.so:system/lib/libdll.so \
    vendor/acer/salsa/proprietary/libcm.so:system/lib/libcm.so \
    vendor/acer/salsa/proprietary/libmmgsdilib.so:system/lib/libmmgsdilib.so \
    vendor/acer/salsa/proprietary/libgsdi_exp.so:system/lib/libgsdi_exp.so \
    vendor/acer/salsa/proprietary/libgstk_exp.so:system/lib/libgstk_exp.so \
    vendor/acer/salsa/proprietary/libwms.so:system/lib/libwms.so \
    vendor/acer/salsa/proprietary/libnv.so:system/lib/libnv.so \
    vendor/acer/salsa/proprietary/libwmsts.so:system/lib/libwmsts.so \
    vendor/acer/salsa/proprietary/libpbmlib.so:system/lib/libpbmlib.so \
    vendor/acer/salsa/proprietary/libdss.so:system/lib/libdss.so \
    vendor/acer/salsa/proprietary/libauth.so:system/lib/libauth.so \
    vendor/acer/salsa/proprietary/liboemcamera.so:system/lib/liboemcamera.so \
    vendor/acer/salsa/proprietary/liboemcamera.so:obj/lib/liboemcamera.so \
    vendor/acer/salsa/proprietary/libcamera.so:system/lib/libcamera.so \
    vendor/acer/salsa/proprietary/libcamera.so:obj/lib/libcamera.so \
    vendor/acer/salsa/proprietary/libmmjpeg.so:system/lib/libmmjpeg.so \
    vendor/acer/salsa/proprietary/libmmipl.so:system/lib/libmmipl.so \
    vendor/acer/salsa/proprietary/libmmparser_divxdrmlib.so:system/lib/libmmparser_divxdrmlib.so \
    vendor/acer/salsa/proprietary/libmmosal.so:system/lib/libmmosal.so \
    vendor/acer/salsa/proprietary/libmmparser.so:system/lib/libmmparser.so \
    vendor/acer/salsa/proprietary/libloc.so:system/lib/libloc.so \
    vendor/acer/salsa/proprietary/libloc.so:obj/lib/libloc.so \
    vendor/acer/salsa/proprietary/libloc-rpc.so:system/lib/libloc-rpc.so \
    vendor/acer/salsa/proprietary/libcommondefs.so:system/lib/libcommondefs.so \
    vendor/acer/salsa/proprietary/sensorcalibutil_yamaha:system/bin/sensorcalibutil_yamaha \
    vendor/acer/salsa/proprietary/sensorserver_yamaha:system/bin/sensorserver_yamaha \
    vendor/acer/salsa/proprietary/sensorstatutil_yamaha:system/bin/sensorstatutil_yamaha \
    vendor/acer/salsa/proprietary/libms3c_yamaha.so:system/lib/libms3c_yamaha.so \
    vendor/acer/salsa/proprietary/libsensor_yamaha.so:system/lib/libsensor_yamaha.so \
    vendor/acer/salsa/proprietary/sensors.salsa.so:system/lib/hw/sensors.salsa.so \
    vendor/acer/salsa/proprietary/libsc-a2xx.so:system/lib/libsc-a2xx.so \
    vendor/acer/salsa/proprietary/eglsubAndroid.so:system/lib/egl/eglsubAndroid.so

